# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-DateTime
version:      0.03
version_from: lib/Catalyst/Plugin/DateTime.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    DateTime:                      0.20

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
